spring:
  application:
    name: nexusprocure

  lifecycle:
    timeout-per-shutdown-phase: 30s

  flyway:
    enabled: true #Spring boot run flyway when application starts
    baseline-on-migrate: true # Does not say I don't know you for postgresql data instead it treats them as starting point.
    baseline-version: 1 # saying the existing data is version 1

  datasource:
     url: ${SPRING_DATASOURCE_URL}
     username: ${SPRING_DATASOURCE_USERNAME}
     password: ${SPRING_DATASOURCE_PASSWORD}

  jpa:
        hibernate:
          ddl-auto: update

        show-sql: true
        properties:
          hibernate:
            format_sql: true

  kafka:
      bootstrap-servers: ${KAFKA_BOOTSTRAP_SERVERS}
      producer:
        key-serializer: org.apache.kafka.common.serialization.StringSerializer
        value-serializer:  org.springframework.kafka.support.serializer.JsonSerializer

      consumer:
        group-id: purchase-order-group
        auto-offset-reset: earliest
        key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
        value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer

        properties:
          spring.json.trusted.packages: "com.nexusprocure.common.event.purchaseorder"

  data:
      web:
        pageable:
         default-page-size: 20
        max-page-size: 100
server:
   shutdown: graceful

jwt:
  secret: ${JWT_SECRET}
  expiration:  ${JWT_EXPIRATION:86400000}

api:
  title: NexusProcureAPI
  description: Enterprise Procurement Management System
  version: 1.0

  contact:
   name: Nexus Procure Development Team
   email: support@nexusprocure.com
   url: https://www.nexusprocure.com

  license:
     name: Apache License 2.0
     url: https://www.apache.org/licenses/LICENSE-2.0

management:
  endpoints:
    web:
      exposure:
        include: health

  endpoint:
    health:
      probes:
        enabled: true



