apiVersion: v1

kind: Pod

metadata:
  name: nexusprocure

spec:
  containers:
    - name: nexusprocure
      image: nexusprocure:latest
      imagePullPolicy: Never
      ports:
      - containerPort: 8080