CREATE TABLE vendors(
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    vendor_code VARCHAR(255) NOT NULL UNIQUE,
    vendor_name VARCHAR(255) NOT NULL,
    email VARCHAR(255) NOT NULL UNIQUE,
    phone VARCHAR(255),
    address VARCHAR(255),
    status VARCHAR(50) NOT NULL,
     CONSTRAINT chk_vendor_status
       CHECK (status IN ('ACTIVE', 'INACTIVE'))
)