name: NexusProcure CD

on:
  workflow_run:  # Why Workflow_run? This workflow is triggered when NexusProcure CI workflow finishes.
    workflows: ["NexusProcure CI"]
    types:
      - completed  # we want CD to be notified whether CI passes or fails.

jobs:
  docker-build-and-push:
    if: ${{ github.event.workflow_run.conclusion == 'success' }} # That's our quality gate.

    runs-on: ubuntu-latest

    steps:
      - name: Checkout source code
        uses: actions/checkout@v4
        with:
          ref: ${{ github.event.workflow_run.head_sha }} # why head_sha? Because, cd is triggered by
          # another completion of workflow which in this case is CI, we want exact commit that CI validated.
          # why this check out is important? Because, we want to build the docker image from exact revised source that CI validate
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          # See we dont have hardcode user name and password github repository retrieves from
          # Encrypted Actions and secrets.
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v6
        with:
          context: .
          push: true
          tags: sagar1414/nexusprocure:${{ github.event.workflow_run.head_sha }}
          # because docker image should have deterministic relationship to the source commit it produces it.
          # traceability: which commit produces this image?
          # Reproductibility: Can I identify exactly what was deployed?
          # Rollback capability: Can i deploy older good images?
  deploy-to-kubernetes:
    needs: docker-build-and-push  # Dont start kubernetes deployment until docker build and push succeded.
    runs-on: [ self-hosted, nexusprocure ] # find self hosted runner which have both labels.

    steps:
      - name: Checkout source code
        uses: actions/checkout@v4  # Hey github actions download/checkout the Gits repository into the runner
        with:
         ref: ${{ github.event.workflow_run.head_sha }} #Which exact version of the source code did that CI workflow run?"
      - name: Verify Kubernetes connection
        run: kubectl get nodes

      - name: Verify Kustomize configuration  # "Can the runner access the repository's k8s/ directory and successfully generate the Kubernetes manifests?"
        run: kubectl kustomize k8s/

      - name: Set image in Kustomize
        shell: powershell
        run: |
          (Get-Content k8s/kustomization.yaml) `
            -replace 'newTag: v4', "newTag: ${{ github.event.workflow_run.head_sha }}" `
            | Set-Content k8s/kustomization.yaml

      - name: Deploy NexusProcure with Kustomize
        run: kubectl apply -k k8s/  # Build final manifests and apply them to cluster

      - name: Record deployed Git commit
        run: kubectl annotate deployment/nexusprocure-deployment --overwrite kubernetes.io/change-cause="Deploy commit ${{ github.event.workflow_run.head_sha }}"
      - name: Wait for rollout
        run: kubectl rollout status deployment/nexusprocure-deployment # if changed so we do roll out status and we wait till pods become healthy and ready to accept the traffic or connections.
